language: python
cache:
  directories: 
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  # python 3.2 deprecated (not supported by pip, setuptools, etc)
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"
# https://docs.travis-ci.com/user/languages/python/

sudo: false

env:
  - PYTHONIOENCODING="UTF-8"

branches:
  only:
    - master

git:
  depth: 10
  # known-bug:
  # fast pushes to github, slow tests (many repos)
  # travis can't clone required commit with small depth (1,2,...)
  # git checkout -qf <sha>
  # fatal: reference is not a tree: <sha>

# https://docs.travis-ci.com/user/notifications/
notifications:
  # https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
  email:
    recipients:
      - continuous.integration.errors@gmail.com
    on_success: never
    on_failure: always
  irc: false
    #channels:
    #  - "chat.freenode.net#russianidiot"
    #on_success: never
    #on_failure: always
    #use_notice: true
    #skip_join: true

before_install:
  - env

install:
  - bash Tests/.sh/install.sh

before_script:
  - pwd

# command to run tests
script:
  - bash Tests/.sh/run.sh

after_script:
  -

after_failure:
  - pwd

# Calculate coverage
#after_success:
  #- coveralls 
  # Couldn't find a repository matching this job.
